class CustomException(Exception):
    pass


class ElementFoundException(CustomException):
    pass
